In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
x = pd.read_csv("train.csv")
df = pd.DataFrame(x)
df['Sex'] = df['Sex'].map({'male': 1, 'female': 0})
df['Embarked'] = df['Embarked'].map({'C' : 1 , 'S' : 2 , 'Q' : 3})
df['Age'] = df['Age'].fillna(df['Age'].mean())
y = df['Survived']
X = df.drop(['Survived' , 'Name', 'Ticket','Cabin'] , axis = 1)



In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.1,
    random_state=42
)
X_train.fillna(X_train['Age'].mean(), inplace = True)

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score


In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
import matplotlib.pyplot as plt
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

In [14]:
y_pred_DT = dtree.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred_DT)
print("Accuracy:", accuracy)

Accuracy: 0.7222222222222222


In [15]:
# Create logistic regression model using 'liblinear' solver
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(solver='liblinear')

# Fit the model to training data
logreg.fit(X_train , y_train)

LogisticRegression(solver='liblinear')

In [16]:
y_pred_LR = logreg.predict(X_test)

In [17]:
precision_score(y_test, y_pred_LR)

0.7837837837837838

In [18]:
from mlxtend.plotting import plot_decision_regions

plot_decision_regions(X_train, y_train, clf=logreg, legend=2)

#library is not installed. also make sure that there are only 2 features in X

ModuleNotFoundError: No module named 'mlxtend'

In [19]:


accuracy = accuracy_score(y_test, y_pred_LR)
print("Accuracy:", accuracy)

Accuracy: 0.8333333333333334


In [20]:
precision_score(y_test, y_pred_LR)

0.7837837837837838

In [21]:
from sklearn.tree import DecisionTreeRegressor
regtree = DecisionTreeRegressor(random_state=42)
regtree.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [22]:
y_pred_RT = regtree.predict(X_test)
accuracy_score(y_test , y_pred_RT)

0.7111111111111111

In [23]:
precision_score(y_test, y_pred_RT)

0.6388888888888888

In [24]:
from sklearn.ensemble import RandomForestClassifier
randomforest = RandomForestClassifier(n_estimators=100, random_state=50)
randomforest.fit(X_train, y_train)

RandomForestClassifier(random_state=50)

In [25]:
y_pred_RF = randomforest.predict(X_test)
accuracy_score(y_pred_RF , y_test)

0.8222222222222222

In [26]:
precision_score(y_test, y_pred_RF)

0.75

In [27]:
from sklearn.ensemble import AdaBoostRegressor
adaboost = AdaBoostRegressor( estimator = None , n_estimators = 75)
adaboost.fit(X_train , y_train)

AdaBoostRegressor(n_estimators=75)

In [28]:
y_pred_AB = (adaboost.predict(X_test))
y_pred_AB

array([0.22752809, 0.22752809, 0.22752809, 0.90909091, 0.61176471,
       0.92222222, 0.61176471, 0.22752809, 0.61176471, 0.90909091,
       0.31      , 0.22752809, 0.        , 0.22752809, 0.22752809,
       0.90410959, 0.44301075, 0.55782313, 0.22752809, 0.31      ,
       0.22752809, 0.33070866, 0.61176471, 0.22752809, 0.22752809,
       0.55862069, 0.31      , 0.22752809, 0.4318618 , 0.61176471,
       0.22752809, 0.61176471, 0.44301075, 0.65909091, 0.22752809,
       0.22752809, 0.31      , 0.61176471, 0.90410959, 0.22752809,
       0.11764706, 0.22752809, 0.22752809, 0.22752809, 0.61176471,
       0.11764706, 0.22752809, 0.22752809, 0.22752809, 0.34586466,
       0.67256637, 0.92222222, 0.33070866, 0.55862069, 0.22752809,
       0.90909091, 0.22752809, 0.90909091, 0.90909091, 0.61176471,
       0.22752809, 0.90909091, 0.90909091, 0.31      , 0.22752809,
       0.90909091, 0.11764706, 0.22752809, 0.22752809, 0.98675497,
       0.90909091, 0.90909091, 0.44301075, 0.92222222, 0.22752

In [29]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [30]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score

confusion_matrix(
    y_test,
    y_pred_LR)

array([[46,  8],
       [ 7, 29]], dtype=int64)

In [31]:
confusion_matrix(
    y_test,
    y_pred_DT)

array([[41, 13],
       [12, 24]], dtype=int64)

In [32]:
confusion_matrix(
    y_test,
    y_pred_RT)

array([[41, 13],
       [13, 23]], dtype=int64)

In [33]:
confusion_matrix(
    y_test,
    y_pred_RF)

array([[44, 10],
       [ 6, 30]], dtype=int64)

In [34]:
import pickle

# Makes files of our models
#  you can use heroku for making website and shit, uploading models 